### ISSUE TITLE
Embed content not working in widgets

### ISSUE THREAD

**Issue by oseg** [ColdTrick/widget_manager#110]
Context: elgg v2.3.3 + widget_manager v8.2 + widget_pack v1.3

Scenario:
- Add a "FreeHTML" widget to a group profile
- Click on the widget gear to configure FreeHTML widget
- Click on "embed content" link
- Select the file to embed
=> both embed popup and configure widget popup are dismissed
=> the selected file page is displayed

**Comment by jdalsem** [comment]
This is also a problem in the latest Elgg 3 versions of the plugins

**Comment by jdalsem** [comment]
Closing this as a duplicate of https://github.com/ColdTrick/embed_extended/issues/16
