### ISSUE TITLE
Index page widget layout problem on small screens

### ISSUE THREAD

**Issue by iionly** [ColdTrick/widget_manager#112]
If you want to have a index page with more than 1 column you currently get a broken layout on small screen.

It's alright on large screen resolutions where the widgets can be placed in multiple columns according to the selected column layout.

But on small screen resolutions the responsive behaviour results in a faulty layout. The problem is when the screen width is low enough for the widgets to be ordered in 1 column below each other the widgets still keep their fraction of total width and don't use the full 100% width instead. Therefore more than 1 column on the index page seems currently not possible to use if you want to have a good layout also on mobile devices. Only option currently seems to be to use a 1 column layout to have all widgets with 100% width on all screen sizes.

**Comment by jdalsem** [comment]
This currently works fine for me, but specific widgets could cause an issue. This is not something that widget_manager would fix i guess

**Comment by iionly** [comment]
@jdalsem It's not for specific widgets only. It's for ALL widgets on the index page if you let Widget Manager provide the index page.

Maybe some clarification: I'm referring to Widget Manager on Elgg 2.x (as I had opened this issue BEFORE Elgg 3 and the corresponding Widget Manager version got released). On Elgg 3 it seems to work fine indeed but not on Elgg 2.3 with Widget Manager 8.3.2.

Here two screenshots to illustrate the problem. I've used the Free HTML widget only with 2 columns (75%/25%) but the problem is the same with any other widgets or any other layout. The problem occurs only on the index page while profile pages, dashboards and group profile pages work fine with different widths.

On full width it looks alright:
![Widget_Manager_Index_Full_width](https://user-images.githubusercontent.com/1773681/56234961-b3352700-6086-11e9-94de-d5d838b84003.png)

but when decreasing width the layout changes to 1 column and from this point on or at any smaller width there should be only 1 column using 100% but the widgets keep their original fraction of width:

![Widget_Manager_Index_Small_width](https://user-images.githubusercontent.com/1773681/56235014-c9db7e00-6086-11e9-9f69-266b760e02cc.png)

**Comment by jdalsem** [comment]
Thanks for clarifying this. I will look into why this behaviour changed in one of the latest Elgg 2.3 versions of this plugin

**Comment by jdalsem** [comment]
Tried to reproduce with all the latest versions and i am unable to reproduce it

**Comment by iionly** [comment]
As it happens I just thought last week that I also need to re-test this issue when logging in to a test site of mine that still had a 3-column index page config.

I need to test more thoroughly but I still see the issue on the test site I used to create the screenshots above. This site is on Elgg 2.3.10 and uses latest Widget Manager / Widget Pack plugin version for Elgg 2.3 with a 2-column index page. On the other test site I have Elgg 2.3.15, the same versions of the plugins and it seems to work perfectly fine there (3-columns on this site but the number of columns seems not matter when I first noticed the problem). So, I need to upgrade the other test site to 2.3.15 to see if the issue is gone then, too.

**Comment by iionly** [comment]
@jdalsem I upgraded the site where I still had the problem to 2.3.15 now and STILL have the problem when setting up the index page in way shown in the image above (two columns with 75% and 25% respectively). The other site had 3 columns (each with 33% width). When I try the same layout on the other site it also works as expected when decreasing the windows width.

So, it seems it might work only if the widgets in the different columns all have the same width to begin with for the re-ordering on decreasing the width to work correctly.

And chance you could try it once more (preferably not only next year :wink: )?

**Comment by iionly** [comment]
I think it's https://github.com/ColdTrick/widget_manager/blob/402a5c0d19773cb31d7b88f98104ff490e165a51/views/default/resources/widget_manager/custom_index.php#L32 not being changeable via css causing the problem if it's not 33/33/33 or 50/50 layout. Can it be even changed for Elgg 2.3?

**Comment by jdalsem** [comment]
Is there a way i can see/test on your site?

**Comment by iionly** [comment]
Sorry. It's on a local test installation where no external access is possible. 

Doesn't it sound plausible that the width set via style is the culprit? Each column is set to 100% width via the elgg-widget call. But the value of width set via style then uses only a fraction of these 100%.
