### ISSUE TITLE
Possibility to add custom widgets

### ISSUE THREAD

**Issue by staion16** [ColdTrick/widget_manager#113]
Nobody want this feature? To be able to add a custom widget? Just a custom HTML widget would be nice.

**Comment by jdalsem** [comment]
there is a custom html widget... widget manager as a plugin does not provide widgets... only widget management features. THere is the widget_pack (https://github.com/ColdTrick/widget_pack) plugin which has various generic widgets.. like the free_html widget. I hope that helps.
