### ISSUE TITLE
Sometimes fixed widgets are not displayed or are displayed in the wrong position

### ISSUE THREAD

**Issue by oseg** [ColdTrick/widget_manager#115]
Context:
- elgg v2.3.14
- widget manager v8.3.2
- enable dashboard plugin

Scenario:
- Go in the Dashboard Default Widgets (/admin/appearance/default_widgets?widget_context=dashboard)
- Add a widget ("Activity" for instance)
- Add a 2nd widget ("Blog" for instance)
=> "Blog" widget is displayed before "Activity" widget. In database, the widget orders are respectively -10 and 0
- Add a new user (/admin/users/add)
=> The 2 default widgets are cloned for the new user dashboard
- Go back in the Dashboard Default Widgets (/admin/appearance/default_widgets?widget_context=dashboard)
- Set the "Activity" widget to "fixed"
=> The fixed "activity" widget should be displayed before the "blog" widget after a page refresh but it is not the case...
- Log in as the new user
- Display the dashboard

Results:
=> "Activity" widget is displayed after "Blog" widget

Expected results:
=> "Activity" widget should be displayed before "Blog" widget because it is a fixed widget

note 1: widget_manager_update_fixed_widgets() fixing order part did not work because the algorithm expects widget orders to be > 0, but sometimes it is not the case.

note 2: In the above scenario, the issue seems minor, but it is not: there are scenarios where some widgets are hidden by other widgets because they have the same "order" value in the database. Moreover if the dashboard default widget timestamp is updated, the hidden widgets may be cloned again in the user dashboards and still not displayed...

note 3: this issue seems to be quite an old bug, and I think it is still there in widget manager v10: I had a quick look and I didn't see any major changes in widget_manager_update_fixed_widgets() algorithm.

**Comment by oseg** [comment]
I can create a pull request on widget_manager master branch if you like, but I won't be able to test it. My dev environment is still under PHP v5.6.

**Comment by jdalsem** [comment]
Fixed widgets feature is removed from the plugin in Elgg 4. https://github.com/ColdTrick/widget_manager/commit/f14469ec145055046ebc67700e5c5dd95a5d8274
This issue will not be fixed
