### ISSUE TITLE
Profile widgets

### ISSUE THREAD

**Issue by andrewga** [ColdTrick/widget_manager#117]
HI, Would it be possible to set what widget and position on all profiles and not allow users to change them or move them around?

**Comment by jdalsem** [comment]
Yes, this is already a feature. You can configure default widgets as an admin (and pin them so they can't be removed)

**Comment by andrewga** [comment]
I cant seem to figure out how to pin the widgets.  I tried the plugin settings of the widget plugin but doesnt work.

**Comment by jdalsem** [comment]
It is not part of the settings... you need to look for 'default widgets' menu item. URL should be `admin/configure_utilities/default_widgets`

**Comment by andrewga** [comment]
I can't seem to get the widgets to fix on the profile page. Could it be because im using elgg 3.2?

**Comment by jdalsem** [comment]
did you find the pin feature on the default widgets page?

**Comment by andrewga** [comment]
Yea, I clicked it and it turned blue. Then I went to to the profile page and it doesnt show the widget

**Comment by oseg** [comment]
Hello,

I tried widget_manager v10.0.2 with elgg v3.2.0 and I confirm andrewga status:

- for existing users, the fixed widget is not displayed.
- for new users, the default widget is added, but it can be removed by the user (not fixed then).

Best,
oseg
