### ISSUE TITLE
Fixed widgets are not displayed

### ISSUE THREAD

**Issue by oseg** [ColdTrick/widget_manager#118]
Context:
- elgg v3.2.0 + widget_manager v10.0.2

Scenario:
- In Administration Configure/Widgets/Default widget, 'Profile' tab: add an "Activity" widget
- On this widget, click on "Fix this widget" pin icon
  => the pin icon becomes blue
- Go to your profile

Results:
- The fixed "activity" widget is not displayed

Expected results:
- The fixed "activity" widget is displayed

Note: it uses to work with elgg v2.3.14 + widget manager v8.3.2

**Comment by oseg** [comment]
related to issue #117

**Comment by jdalsem** [comment]
Fixed widgets feature has been removed from this plugin in Elgg 4. https://github.com/ColdTrick/widget_manager/commit/f14469ec145055046ebc67700e5c5dd95a5d8274

This issue will not be fixed
