### ISSUE TITLE
Pinning a Widget by Admin makes it appear multiple times in Member Profile

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/widget_manager#122]
**Elgg version**
3.3.6

**Plugin version**
widget_manager_v9.0

**Plugin source**
- Elgg community page download
- Github releases download

**Describe the bug**
Pinning a Widget (by Site Admin) makes it appear TWICE in Member Profile page

**To Reproduce**
1. Go to '../admin/configure_utilities/default_widgets?widget_context=profile'
2. Click on 'Pin' of any widget : e.g. Activity ( or Blog etc) and it turns blue
3. In Member Profile page it appears twice
4. Login as the member : he  cannot delete the duplicates and has multiple duplicate widgets in Profile 

**Expected behavior**
In User Profile Page it should be pinned and appear ONCE only

**Screenshots**
 
![8a](https://user-images.githubusercontent.com/43325988/84959822-bfe75c00-b11d-11ea-8816-8bbbfd500b50.png)

**Additional context**
I think this is not what used to happen in previous versions of Elgg &/or this plugin.
This is a new and unexpected problem apparently.
May be in "admin/widgets/manage" a further column by the side of "Can be added" there can be a "Can be dragged/moved"  - I am not sure, but this can help solve the "Pin" problem. While, if a new Pin has been done, it will not affect site-wide previous users, but "Can be added" on-off can affect  both previous and new users. Thus, if "Can be dragged" is there, it can affect both previous and new users - a desirable way to change something in the site.

**Comment by jdalsem** [comment]
This feature has been removed from the plugin https://github.com/ColdTrick/widget_manager/commit/f14469ec145055046ebc67700e5c5dd95a5d8274 for Elgg 4.0. This issue will not be fixed

**Comment by daniyaree** [comment]
@jdalsem  Thanks. This is sad as this was the most important stuff (for the site-admin) and it worked fine, except the fact that pinning made a widget appear twice. The Readme md says "Forcing of widget (incl positioning) on profile/dashboard (also later!)" - how do we do this? Is there any other way? Thanks.

**Comment by jdalsem** [comment]
@daniyaree we have had no customers using this specific feature of Widget Manager for over a few years, so it was a badly maintained part of the plugin. It is also a feature that was very difficult to make and hard to understand. Thanks for letting me know it is still in the README. I will remove it. There is no other way. You sometimes need to let go...

**Comment by daniyaree** [comment]
@jdalsem  Yes, I understand. I am sorry to know. I also understand that we need monetization or sponsorship for certain things. Basically I do non-profit sites but will surely be trying to get in touch regarding possible amount ($) needed for some simple features that were/are already there to be back in action. Also an off-topic request : Github sponsorship for ColdTrick is now set only to monthly mode and no one-time mode is available. As there are very recent problems with international CC recurrent billing please consider turning on also the one-time mode. Thanks for your responses.

**Comment by jdalsem** [comment]
@daniyaree the one-time option is now available. Thanks for the tip
