### ISSUE TITLE
Fatal Error on Saving Plugin settings

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/widget_manager#124]
**Elgg version**
Elgg 4.0.0 Stable Release - September 24, 2021  & php8x

**Plugin version**
latest as available in github now

**Plugin source**
Github releases download

**Describe the bug**
Visit Plugin Settings: Widget Manager. Click "Save". Fatal Error & Blue screen showing nothing except the error message.

**To Reproduce**
1. Go to 'Visit Plugin Settings: Widget Manager.'
2. Click on 'Save'
3. Scroll down not needed

```
Fatal Error.
An unrecoverable error has occurred and has been logged. Contact the site administrator with the following information:
Exception at time 2021-09-27T23:39:26+00:00.
```

**Expected behavior**
Plugin settings will be saved without any error

**Additional context**
php8x is being used. Only default Elgg install - fresh! and no other extra plugins.

**Comment by jdalsem** [comment]
Thanks for reporting! Bug found and fixed. Could you next time try to add the webserver error log that is related to this error?

**Comment by daniyaree** [comment]
@jdalsem  many many thanks. Sure I will try to do that. Thanks.
