### ISSUE TITLE
Added widgets remain blank or show no contents in index page

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/widget_manager#125]
**Elgg version**
Elgg 4.0.0 Stable Release - September 24, 2021 & php8x

**Plugin version**
latest as available in github now

**Plugin source**
Github releases download

**Describe the bug**
Added widgets remain blank in index page

**To Reproduce**
1. Add Widgets in index page, for example, Activity | Blog etc
2. do some activity, post a blog
3. The widgets remain blank, while the actual /activity or blog page shows all activities

**Expected behavior**
The widget should show Activity stream

**Additional context**
php8x is being used. Only default Elgg install - fresh! and no other extra plugins.

**Comment by jdalsem** [comment]
With stock Elgg it is not possible to add the activity widget to the index page... maybe you have exposed the widget (manage widgets as admin) to the homepage. This action is not without risk... not all widget (that do not declare it themselves) work on the index page. For the default 'activity' widget this is the case... it will not work on the homepage (it is designed for the profile and dashboard page).

If you need an activity widget that works on the homepage i would suggest you install the Widget Pack (https://github.com/ColdTrick/widget_pack) plugin. It contains a widget call 'index_activity' that works on the homepage.
