### ISSUE TITLE
Can widget position be kept fixed by the admin but allow end-user-edit of the widgets.

### ISSUE THREAD

**Issue by rhisss** [ColdTrick/widget_manager#47]
Can widget position be kept fixed by the admin but allow end-user-edit of the widgets.
For example, allow Blog widget on top right corner of Profile page and fix/pin it there - it does so but the user setting options are also lost (eg if user wants to show 5 or 10 posts etc)

**Comment by jdalsem** [comment]
Fixed widgets are no longer a feature of Widget Manager in Elgg 4. https://github.com/ColdTrick/widget_manager/commit/f14469ec145055046ebc67700e5c5dd95a5d8274
