### ISSUE TITLE
Support Request: Trying to make liquid-width unequal-width columns of Widgets

### ISSUE THREAD

**Issue by rhisss** [ColdTrick/widget_manager#57]
<code>#elgg-widget-col-3  {width :28%}
#elgg-widget-col-2  {width :43%}
#elgg-widget-col-1  {width :28%}</code>
I do get a middle wider column and two less wide right and left column but when the browser is collapsed to give a mobile view, the wider column becomes disproportionately narrow with texts into almost unreadable narrow lines

How can I just fall back to <code> .elgg-col-1of3 {width :33%}</code> when its a mobile screen or just when a browser window has been resized to a narrow proportion by the viewer? Any css-trick idea?

**Comment by jdalsem** [comment]
You can use `@media` css declarations to have different css for different screen sizes. For an example look here: https://github.com/Elgg/Elgg/blob/1.10/mod/aalborg_theme/views/default/aalborg_theme/css.php#L110
