### ISSUE TITLE
Twitter widget does not keep twitter code

### ISSUE THREAD

**Issue by gerard-kanters** [ColdTrick/widget_manager#59]
When adding the twitter code and saving, it displays fine. If you then want to change the height in pixels, the widget code is gone. If a user does not notice that, he has to look up the widget code again and paste it again. This happens both in groups and on the profile page.This happens in v4.8

**Comment by jdalsem** [comment]
The widget code is not saved with the widget, but only the widget id. It is scraped from the widget code (as most people do not know where to find the id). If you edit the widget again and do not supply any code, the id is not changed, so you should be able to change the height only and not loose the widget id

**Comment by gerard-kanters** [comment]
I agree that that is how it should work, but it doesn't do that here in multiple sites. The ID is not saved the second time and lost. The ID is also not shown when editing the widget

**Comment by jdalsem** [comment]
it is correct that the id is not shown. I am able to edit the widget changing height without loosing any content, so i can not reproduce your issue (in master version).

**Comment by gerard-kanters** [comment]
I am using v4.7 (latest stable release for 1.8) I cannot use the master since the sites are not 1.9 or higher.

**Comment by jdalsem** [comment]
Tried again to reproduce this on v4.7, but still can not reproduce this.
