### ISSUE TITLE
wrong link to favorite/toggle

### ISSUE THREAD

**Issue by Pasley70** [ColdTrick/widget_manager#60]
The script /lib/widgets.php register the action "favorite/toggle" with the following link:

    elgg_get_plugins_path() . "widget_manager/actions/favorites/toggle.php"

but the file lies here:

    path/to/plugin/widget_manager/actions/favorites/actions/toggle.php

This leads to the error message "The action file for favorite/toggle was not found." If you move "toggle.php" one level lower into the folder "favorites", the error message is no longer shown.

**Comment by jdalsem** [comment]
thnx for reporting... should be fixed now
