### ISSUE TITLE
Add admin option to enable advanced widget config on all locations

### ISSUE THREAD

**Issue by olairmarcos** [ColdTrick/widget_manager#72]
It is important to have (option enable) all advanced widget settings for profile, group and dashboard within the widget_manager configuration panel.
Thanks for listening.

**Comment by jdalsem** [comment]
Do wish this for the admin or also for the user configuring the widget?

**Comment by olairmarcos** [comment]
In the config advanced Widget: The administrator can not access the advanced settings widget, then insert the widget in profile, group and dashboard.
If you need to hide (Hide Header) can not hide.
It is possible to enable advanced settings to Default widget. At the moment only it is possible to set (Custom Custom title and title link) on the widget.

In manage widget: When hide the widget to the user, the administrator can not embed the widget into (default widget to profile, group and dashboard). It is wise to hide the user and not hide for the administrator.
Thanks for listening.

**Comment by jdalsem** [comment]
This FR feels too exotic. The advanced options should not be used by regular users or on 'normal' contexts like profile or groups.
