### ISSUE TITLE
Groups widget - add buttons

### ISSUE THREAD

**Issue by nlybe** [ColdTrick/widget_manager#75]
I tested 6.0-beta on more than one Elgg 2.0 sites. When using widget manager on groups, on lightbox window the button "Add widget" is still available even for widgets I have already added on group.
See the attachment
Nikos

![1](https://cloud.githubusercontent.com/assets/4714025/13591093/233295f0-e4ee-11e5-9e75-d633664c2364.png)

**Comment by jdalsem** [comment]
This is correct. The widgets that i see in the screenshot are allowed to be added multiple times... There currently is no feedback that the widget is added to the widgets list on the group profile, other than the fact that the widget is added (but that is hard to see, as it is behind the lightbox :))

**Comment by nlybe** [comment]
Thanks for quick feedback. Actually it happens with other widgets too like "Group Activity" (from group tools plugin). In previous versions for Elgg 1.1x could add it just once, which make sense to me.

**Comment by jdalsem** [comment]
i tested this locally and i can not add multiple widgets that are marked as 'single' on a group page
