### ISSUE TITLE
Race condition in widget initialization

### ISSUE THREAD

**Issue by hypeJunction** [ColdTrick/widget_manager#76]
Error on group profile where widgets are not rendered due to group privacy:

`Uncaught Error: cannot call methods on sortable prior to initialization; attempted to call method 'option'`

`site.js` should probably check if `.elgg-widgets` has a length

**Comment by hypeJunction** [comment]
This also happens with widgets present. Seems to be a result of https://github.com/Elgg/Elgg/pull/9407

**Comment by mrclay** [comment]
https://github.com/Elgg/Elgg/pull/9525 will help, but site.js will need to wait for the `init, system` hook.
