### ISSUE TITLE
MultiDashboard::save() overwrites attribute values

### ISSUE THREAD

**Issue by hypeJunction** [ColdTrick/widget_manager#78]
I am creating a MultiDashboard instance programmatically and save() keeps overwriting my owner and container values.

**Comment by jdalsem** [comment]
can't you just set your attributes after the first save?

**Comment by hypeJunction** [comment]
I ended up using ElggObject and setting the subtype.

**Comment by hypeJunction** [comment]
The problem with your suggestion is that event handlers receive wrong owner/container information on save.

**Comment by jdalsem** [comment]
Yep, do you have a suggestion how this could be fixed?

**Comment by jdalsem** [comment]
probably we should move the attributes to the initialize attributes function instead of having it in the save action....

**Comment by hypeJunction** [comment]
Depends why you added them in the first place. Owner and container default to logged in user already, so I guess if you set the access in initialize attributes that should be enough.
