### ISSUE TITLE
Only show tab settings icon if can edit

### ISSUE THREAD

**Issue by hypeJunction** [ColdTrick/widget_manager#80]
Tab settings icon is visible even if user can't edit the tab

**Comment by hypeJunction** [comment]
Meaning if I override the permissions the icon is still there

**Comment by jdalsem** [comment]
There are more features related to the tabs that assume that tabs can always be edited... like dragdrop reordering of tabs and moving widgets to tabs.... if you can make a PR so edit link is only available if canEdit i can merge it.

**Comment by hypeJunction** [comment]
I am working with 5.x release, so if you can branch that out on github, I can make pull requests, you can then merge into master.

**Comment by hypeJunction** [comment]
Maybe that doesn't make much sense. I will make PRs to master.
