### ISSUE TITLE
Fatal Error in pages widget

### ISSUE THREAD

**Issue by merilturock** [ColdTrick/widget_manager#91]
I am getting a Fatal error in some users profile page .. once i unregister the widget pages the fatal error is gone.

Kindly find the discussion about this error in Elgg. 
https://elgg.org/discussion/view/2609512/fatal-error-in-some-user-profile-after-activating-pages-plugin

Thank you
Meril

**Comment by jdalsem** [comment]
I am unable to reproduce this issue and am not experiencing a similar issue anywhere else. It looks like an widget entity is missing a container entity. I do not believe the cause of that problem is somewhere inside this plugin. If you come across more information, please let me know.
